apiVersion: dockyard.dev/v1alpha1
name: grafana
description: Grafana dashboards package.
version: 0.1.0
appVersion: 11.2.0
type: application
compose:
  base: compose.yaml
  overlays: {}
security:
  requireNonRoot: false
  requireHealthchecks: true
  requireReadOnlyRootFilesystem: false
  requireNoNewPrivileges: true
  requireCapDropAll: false
  disallowPrivileged: true
  disallowHostNetwork: true
  disallowDockerSocketMount: true
  disallowHostPathMounts: true
  disallowLatestTag: true
